import Link from "next/link";
import { CodeBlock } from "@/components/code-block";

export const metadata = { title: "Installation" };

export default function Page() {
  return <article className="prose-page max-w-195 m-auto [&_.doc-section_.code-block]:my-[18px] [&_.doc-section_.code-block]:mx-0"><div className="breadcrumb text-[12px] text-muted-foreground mb-5 flex items-center gap-[10px] [&_span]:opacity-[.5] max-[700px]:text-[11px] max-[700px]:mb-4">Start here <span>/</span> Installation</div><h1>Installation</h1><p className="intro text-muted-foreground text-[16px] mt-[14px] leading-[1.6] max-w-160 max-[700px]:text-[14px]">One package. A shared foundation for your apps.</p>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>1. Authenticate</h2><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">GitHub Packages requires authentication even for public npm packages. Create a classic GitHub token with read:packages using an account that can access the package. Configure the registry with an environment-variable placeholder, never the token itself.</p><CodeBlock label=".npmrc" code={'@jnpll:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}'} /><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Supply NODE_AUTH_TOKEN in your shell before installing. This Bash/zsh prompt keeps the token out of shell history and terminal output. npm does not load Next.js .env.local files.</p><CodeBlock label="shell" code={'printf \'GitHub package token: \'\nread -rs NODE_AUTH_TOKEN\nprintf \'\\n\'\nexport NODE_AUTH_TOKEN'} /></section>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>2. Add the dependency</h2><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Version 0.4.0 is available from GitHub Packages. React 19 and Tailwind CSS 4 are required. No local library checkout is needed.</p><CodeBlock label="shell" code={'npm install @jnpll/elements-ui@0.4.0'} /></section>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>3. Connect the theme</h2><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Import the stylesheet in your global CSS, after Tailwind. Adjust the source path relative to that file so Tailwind scans the package classes.</p><CodeBlock label="globals.css" code={'@import "tailwindcss";\n@import "@jnpll/elements-ui/themes.css";\n\n@source "../../node_modules/@jnpll/elements-ui/dist";'} /></section>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>4. Import a component</h2><CodeBlock code={'import { Button } from "@jnpll/elements-ui/button";\n\nexport function SaveAction() {\n  return <Button>Save changes</Button>;\n}'} /><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Import components through their package exports. For Next.js, place interactive examples in a client component. Add the dark class to the document element for dark mode.</p></section>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>Deploy to Vercel</h2><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Create a dedicated classic GitHub token with only read:packages. In your Vercel project settings, add NODE_AUTH_TOKEN as a sensitive environment variable for Production and Preview, then redeploy. Keep the token out of source control and never prefix it with NEXT_PUBLIC_. The .npmrc above authenticates package installation during the build.</p></section>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>Theme switching</h2><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Available in version 0.4.0. The themes.css import loads all bundled palettes. Wrap your app once with the provider; the selector applies and remembers a palette without changing light/dark mode.</p><CodeBlock code={'"use client";\nimport { ElementsThemeProvider } from "@jnpll/elements-ui/theme-provider";\nimport { ThemeSelector } from "@jnpll/elements-ui/theme-selector";\n\nexport function App({ children }) {\n  return <ElementsThemeProvider storageKey="my-app-design">\n    <ThemeSelector />\n    {children}\n  </ElementsThemeProvider>;\n}'} /><CodeBlock code={'import { useElementsTheme } from "@jnpll/elements-ui/theme-provider";\n\nconst { selection, setTheme } = useElementsTheme();\nsetTheme({ theme: "britanniae", palette: "arthur" });'} /><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Use semantic color and geometry tokens throughout your app. Customize defaultSelection, storageKey, persist, or the themes registry on the provider. For server-rendered apps, insert getElementsThemeScript from the themes export in the document head using the same options to restore selections before paint.</p></section>
    <Link className="text-link inline-flex items-center gap-[6px] text-[12px] font-medium [&:hover]:text-primary" href="/components/button">Explore Button</Link>
  </article>;
}
