"use client";

import { IconTooltip } from "@/components/icon-tooltip";

import { useState } from "react";
import { ArrowRight, Check, Folder, LayoutGrid, Monitor, Plus, RotateCcw, Search, Settings, Smartphone } from "lucide-react";
import { Button } from "@jnpll/elements-ui/button";
import { Badge } from "@jnpll/elements-ui/badge";
import { Card, CardContent } from "@jnpll/elements-ui/card";
import { Input } from "@jnpll/elements-ui/input";
import { Switch } from "@jnpll/elements-ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@jnpll/elements-ui/tabs";
import { themes } from "@/collections/themes";
import { useDesignTheme } from "@/components/theme-provider";
import { isLayoutId, type LayoutId } from "@/lib/layouts";
const seedProjects = [
  { name: "Brand refresh", owner: "Eleanor", status: "In progress", progress: 72 },
  { name: "Customer portal", owner: "James", status: "In review", progress: 91 },
  { name: "Autumn collection", owner: "Freya", status: "In progress", progress: 43 },
  { name: "Design foundations", owner: "Oliver", status: "Complete", progress: 100 },
];
const seedTasks = [
  { id: 1, title: "Explore typography", category: "Design", owner: "EL", stage: 0 },
  { id: 2, title: "Review color contrast", category: "Accessibility", owner: "FR", stage: 0 },
  { id: 3, title: "Build navigation", category: "Engineering", owner: "JA", stage: 1 },
  { id: 4, title: "Publish design tokens", category: "Design", owner: "OL", stage: 2 },
];

export function LayoutGallery({ initialLayout = "overview" }: { initialLayout?: LayoutId }) {
  const { selection, select } = useDesignTheme();
  const theme = themes.find(theme => theme.id === selection.theme)!;
  const [layout, setLayout] = useState(initialLayout);
  const [mobile, setMobile] = useState(false);
  const [projects, setProjects] = useState(seedProjects);
  const [tasks, setTasks] = useState(seedTasks);
  const [query, setQuery] = useState("");
  const [creating, setCreating] = useState(false);
  const [projectName, setProjectName] = useState("");
  const [name, setName] = useState("Eleanor Morgan");
  const [email, setEmail] = useState("eleanor@example.com");
  const [notifications, setNotifications] = useState(true);
  const [digest, setDigest] = useState(false);
  const [status, setStatus] = useState("");
  function choose(value: LayoutId) { setLayout(value); setStatus(""); window.history.replaceState(null, "", `/playground?layout=${value}`); }
  function reset() { setProjects(seedProjects); setTasks(seedTasks); setQuery(""); setCreating(false); setProjectName(""); setName("Eleanor Morgan"); setEmail("eleanor@example.com"); setNotifications(true); setDigest(false); setStatus(""); }
  return <article className="layout-gallery max-w-300 m-auto min-w-0">
    <div className="breadcrumb text-[12px] text-muted-foreground mb-5 flex items-center gap-[10px] [&_span]:opacity-[.5] max-[700px]:text-[11px] max-[700px]:mb-4">Workspace <span>/</span> Playground</div><h1>Playground</h1>
    <Tabs value={layout} onValueChange={value => { if (isLayoutId(value)) choose(value); }}>
    <div className="layout-controls flex items-end flex-wrap gap-4 mt-7 mr-0 mb-5 ml-0 max-[760px]:gap-3">
      <TabsList aria-label="Sample layout"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="board">Board</TabsTrigger><TabsTrigger value="settings">Settings</TabsTrigger></TabsList>
      <div className="layout-theme-controls flex gap-3 ml-auto [&_label]:grid [&_label]:gap-[5px] [&_label]:text-[11px] [&_label]:text-muted-foreground [&_select]:min-w-[115px] [&_select]:h-8 [&_select]:py-0 [&_select]:px-2 [&_select]:text-foreground [&_select]:bg-card [&_select]:border [&_select]:border-border [&_select]:rounded-[4px] max-[760px]:ml-0 max-[760px]:[&_select]:min-w-25"><label>Theme<select aria-label="Layout theme" value={selection.theme} onChange={event => { const next = themes.find(theme => theme.id === event.target.value)!; select({ theme: next.id, palette: next.defaultPalette }); }}>{themes.map(theme => <option key={theme.id} value={theme.id}>{theme.name}</option>)}</select></label><label>Palette<select aria-label="Layout palette" value={selection.palette} onChange={event => select({ theme: theme.id, palette: event.target.value })}>{theme.palettes.map(palette => <option key={palette.id} value={palette.id}>{palette.name}</option>)}</select></label></div>
      <div className="layout-view-controls flex gap-[3px]" role="group" aria-label="Layout preview width"><IconTooltip label="Desktop layout preview"><Button size="icon-sm" variant={mobile ? "ghost" : "secondary"} onClick={() => setMobile(false)} aria-label="Desktop layout preview" aria-pressed={!mobile}><Monitor /></Button></IconTooltip><IconTooltip label="Mobile layout preview"><Button size="icon-sm" variant={mobile ? "secondary" : "ghost"} onClick={() => setMobile(true)} aria-label="Mobile layout preview" aria-pressed={mobile}><Smartphone /></Button></IconTooltip><IconTooltip label="Reset sample data"><Button size="icon-sm" variant="ghost" onClick={reset} aria-label="Reset sample data"><RotateCcw /></Button></IconTooltip></div>
    </div>
    <TabsContent value={layout}><div className="layout-surface p-5 bg-muted border border-border rounded-[6px] max-[760px]:p-2"><section className={`sample-app @container [&.sample-app-mobile]:w-90 w-full max-w-full m-auto min-h-140 bg-background text-foreground border border-border rounded-[4px] overflow-hidden ${mobile ? "sample-app-mobile" : ""}`} aria-label="Sample application">
      <header className="sample-header min-h-[58px] py-3 px-5 flex items-center gap-[14px] border-b border-border bg-card [&_>_.sample-avatar]:ml-auto @max-[380px]:p-3 @max-[380px]:gap-2"><span className="sample-logo flex items-center gap-2 font-semibold text-[13px]"><LayoutGrid size={18} />North Studio</span><Badge variant="secondary">Workspace</Badge><span className="sample-avatar grid place-items-center w-7 h-7 rounded-[4px] bg-secondary text-secondary-foreground font-mono text-[10px] shrink-0" aria-label="Eleanor Morgan">EM</span></header>
      <div className="sample-body grid grid-cols-[145px_minmax(0,_1fr)] min-h-125 @max-[660px]:grid-cols-1"><nav className="sample-navigation flex flex-col gap-2 py-5 px-3 border-r border-border bg-card [&_[data-slot='button']]:justify-start @max-[660px]:flex-row @max-[660px]:flex-wrap @max-[660px]:border-r-0 @max-[660px]:border-b @max-[660px]:border-border @max-[660px]:p-3" aria-label="Sample navigation">{[{ id: "overview", name: "Overview", icon: LayoutGrid }, { id: "board", name: "Projects", icon: Folder }, { id: "settings", name: "Settings", icon: Settings }].map(item => <Button key={item.id} variant={layout === item.id ? "secondary" : "ghost"} onClick={() => choose(item.id as LayoutId)} aria-current={layout === item.id ? "page" : undefined}><item.icon />{item.name}</Button>)}</nav>
      <div className="sample-content min-w-0 p-7 @max-[660px]:py-5 @max-[660px]:px-4">
        {layout === "overview" && <>
          <div className="sample-title flex items-center justify-between gap-4 flex-wrap mb-6 [&_h2]:text-[21px] [&_h2]:my-[5px] [&_h2]:mx-0 [&_p:not(.sample-eyebrow)]:text-[12px] [&_p:not(.sample-eyebrow)]:text-muted-foreground @max-[380px]:[&_h2]:text-[19px]"><div><p className="sample-eyebrow text-[10px] text-muted-foreground">Studio overview</p><h2>Good morning, Eleanor</h2><p>Here&apos;s where your projects stand.</p></div><Button onClick={() => setCreating(value => !value)}><Plus />New project</Button></div>
          {creating && <form className="sample-create flex items-center gap-[10px] flex-wrap mb-6 [&_label]:text-[12px] [&_input]:w-45" onSubmit={event => { event.preventDefault(); if (!projectName.trim()) return; setProjects(current => [...current, { name: projectName.trim(), owner: "Eleanor", status: "In progress", progress: 0 }]); setProjectName(""); setCreating(false); setStatus("Project created."); }}><label htmlFor="sample-project-name">Project name</label><Input id="sample-project-name" value={projectName} onChange={event => setProjectName(event.target.value)} required autoFocus /><Button type="submit">Create project</Button></form>}
          <div className="sample-metrics grid grid-cols-3 gap-3 mb-7 [&_[data-slot='card']]:py-4 [&_[data-slot='card-content']]:grid [&_[data-slot='card-content']]:gap-[7px] [&_[data-slot='card-content']]:px-4 [&_span]:text-[11px] [&_span]:text-muted-foreground [&_strong]:text-[28px] [&_strong]:font-semibold [&_strong]:leading-[1.2] [&_small]:text-muted-foreground [&_small]:text-[10px] @max-[380px]:grid-cols-1">{[{ label: "Active projects", value: projects.filter(project => project.status !== "Complete").length, detail: "Across the studio" }, { label: "Tasks completed", value: tasks.filter(task => task.stage === 2).length, detail: "This week" }, { label: "Team capacity", value: "78%", detail: "Room for new work" }].map(metric => <Card key={metric.label}><CardContent><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.detail}</small></CardContent></Card>)}</div>
          <section className="sample-projects"><div className="sample-section-title flex items-center justify-between gap-3 flex-wrap mb-[14px] [&_h3]:text-[13px]"><h3>Projects</h3><div className="sample-search flex items-center gap-2 text-muted-foreground w-45 max-w-full"><Search size={15} /><Input aria-label="Search sample projects" placeholder="Search projects" value={query} onChange={event => setQuery(event.target.value)} /></div></div><div className="sample-table-scroll overflow-x-auto [&_table]:min-w-130 [&_table]:m-0 [&_table]:w-full [&_th]:py-[13px] [&_th]:px-2 [&_td]:py-[13px] [&_td]:px-2 [&_th]:text-left [&_td]:text-left [&_th]:text-[11px] [&_td]:text-[11px] [&_th]:whitespace-nowrap [&_td]:whitespace-nowrap [&_th]:text-muted-foreground [&_th]:font-medium"><table><thead><tr><th>Project</th><th>Owner</th><th>Status</th><th>Progress</th></tr></thead><tbody>{projects.filter(project => project.name.toLowerCase().includes(query.toLowerCase())).map((project, index) => <tr key={`${project.name}-${index}`}><td>{project.name}</td><td>{project.owner}</td><td><Badge variant={project.status === "Complete" ? "default" : "secondary"}>{project.status}</Badge></td><td><div className="sample-progress flex items-center gap-2 font-mono text-[10px] [&_progress]:w-13 [&_progress]:h-[5px] [&_progress]:border-0 [&_progress]:rounded-[2px] [&_progress]:bg-muted [&_progress]:accent-primary"><progress max={100} value={project.progress} aria-label={`${project.name} progress`} /><span>{project.progress}%</span></div></td></tr>)}</tbody></table></div>{!projects.some(project => project.name.toLowerCase().includes(query.toLowerCase())) && <p className="sample-empty py-6 px-0 text-[12px] text-muted-foreground">No projects found.</p>}</section>
        </>}
        {layout === "board" && <><div className="sample-title flex items-center justify-between gap-4 flex-wrap mb-6 [&_h2]:text-[21px] [&_h2]:my-[5px] [&_h2]:mx-0 [&_p:not(.sample-eyebrow)]:text-[12px] [&_p:not(.sample-eyebrow)]:text-muted-foreground @max-[380px]:[&_h2]:text-[19px]"><div><p className="sample-eyebrow text-[10px] text-muted-foreground">Design system / Sprint 04</p><h2>Project board</h2><p>A shared foundation, one task at a time.</p></div><Badge variant="outline">{tasks.length} tasks</Badge></div><div className="sample-board grid grid-cols-3 gap-[18px] [&_>_section]:min-w-0 [&_[data-slot='card']]:mb-3 [&_[data-slot='card-content']]:px-[14px] @max-[660px]:grid-cols-1">{["To do", "In progress", "Done"].map((stage, index) => <section key={stage} aria-label={stage}><div className="sample-section-title flex items-center justify-between gap-3 flex-wrap mb-[14px] [&_h3]:text-[13px]"><h3>{stage}</h3><Badge variant="secondary">{tasks.filter(task => task.stage === index).length}</Badge></div>{tasks.filter(task => task.stage === index).map(task => <Card key={task.id} size="sm"><CardContent><Badge variant="outline">{task.category}</Badge><h3 className="sample-task-title mt-[14px] mr-0 mb-[18px] ml-0 text-[13px] [overflow-wrap:anywhere]">{task.title}</h3><div className="sample-task-footer flex items-center justify-between gap-2"><span className="sample-avatar grid place-items-center w-7 h-7 rounded-[4px] bg-secondary text-secondary-foreground font-mono text-[10px] shrink-0">{task.owner}</span><IconTooltip label={index === 2 ? `Reopen ${task.title}` : `Advance ${task.title}`}><Button size="icon-sm" variant="ghost" aria-label={index === 2 ? `Reopen ${task.title}` : `Advance ${task.title}`} onClick={() => { setTasks(current => current.map(item => item.id === task.id ? { ...item, stage: (item.stage + 1) % 3 } : item)); setStatus(`${task.title} moved to ${index === 2 ? "To do" : index === 0 ? "In progress" : "Done"}.`); }}>{index === 2 ? <RotateCcw /> : <ArrowRight />}</Button></IconTooltip></div></CardContent></Card>)}</section>)}</div></>}
        {layout === "settings" && <><div className="sample-title flex items-center justify-between gap-4 flex-wrap mb-6 [&_h2]:text-[21px] [&_h2]:my-[5px] [&_h2]:mx-0 [&_p:not(.sample-eyebrow)]:text-[12px] [&_p:not(.sample-eyebrow)]:text-muted-foreground @max-[380px]:[&_h2]:text-[19px]"><div><p className="sample-eyebrow text-[10px] text-muted-foreground">Workspace preferences</p><h2>Account settings</h2><p>Your profile and notifications.</p></div></div><form className="sample-settings max-w-140 [&_>_h3]:mt-6 [&_>_h3]:mr-0 [&_>_h3]:mb-4 [&_>_h3]:ml-0" onSubmit={event => { event.preventDefault(); setStatus("Changes saved in this preview."); }}><h3>Profile</h3><div className="sample-form-grid grid grid-cols-2 gap-4 [&_label]:grid [&_label]:gap-2 [&_label]:text-[12px] [&_label]:min-w-0 @max-[660px]:grid-cols-1"><label>Full name<Input required value={name} onChange={event => { setName(event.target.value); setStatus(""); }} /></label><label>Email address<Input type="email" required value={email} onChange={event => { setEmail(event.target.value); setStatus(""); }} /></label></div><h3>Notifications</h3><div className="sample-preference flex items-center justify-between gap-5 py-4 px-0 border-b border-border [&_label]:text-[12px] [&_label]:font-medium [&_p]:text-muted-foreground [&_p]:text-[11px] [&_p]:mt-[3px]"><div><label htmlFor="sample-notifications">Project updates</label><p>Activity from your team and projects.</p></div><Switch id="sample-notifications" checked={notifications} onCheckedChange={setNotifications} /></div><div className="sample-preference flex items-center justify-between gap-5 py-4 px-0 border-b border-border [&_label]:text-[12px] [&_label]:font-medium [&_p]:text-muted-foreground [&_p]:text-[11px] [&_p]:mt-[3px]"><div><label htmlFor="sample-digest">Weekly digest</label><p>A summary of the week&apos;s progress.</p></div><Switch id="sample-digest" checked={digest} onCheckedChange={setDigest} /></div><div className="sample-save mt-6"><Button type="submit"><Check />Save changes</Button></div></form></>}
        <p className="sample-status min-h-[22px] mt-4 text-[12px] text-foreground" role="status">{status}</p>
      </div></div>
    </section></div></TabsContent></Tabs>
  </article>;
}
