import { CodeBlock } from "@/components/code-block";

export const metadata = { title: "Theme & tokens" };
const tokens = ["background", "foreground", "card", "primary", "secondary", "muted", "accent", "border", "ring", "destructive"];

export default function Page() {
  return <article className="prose-page max-w-195 m-auto [&_.doc-section_.code-block]:my-[18px] [&_.doc-section_.code-block]:mx-0"><div className="breadcrumb text-[12px] text-muted-foreground mb-5 flex items-center gap-[10px] [&_span]:opacity-[.5] max-[700px]:text-[11px] max-[700px]:mb-4">Start here <span>/</span> Design foundations</div><h1>Theme & tokens</h1><p className="intro text-muted-foreground text-[16px] mt-[14px] leading-[1.6] max-w-160 max-[700px]:text-[14px]">Neutral surfaces. Clear hierarchy. A consistent vocabulary.</p>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>Semantic colors</h2><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Components use semantic CSS variables. Each token adapts to the current light or dark theme.</p><div className="token-grid grid grid-cols-2 gap-y-0 gap-x-7 max-[700px]:gap-y-0 max-[700px]:gap-x-4 max-[380px]:grid-cols-[1fr]">{tokens.map((token) => <div key={token} className="token-item flex gap-[14px] items-center border-b border-border py-4 px-0 min-w-0 [&_span]:block [&_span]:text-muted-foreground [&_span]:text-[11px] max-[700px]:gap-[10px] max-[700px]:[&_code]:text-[10px]"><div className="token-swatch w-11 h-11 shrink-0 border border-border rounded-[6px] max-[700px]:w-8 max-[700px]:h-8" style={{ background: `var(--${token})` }} /><div><code>--{token}</code><span>{token === "foreground" ? "Text and icons" : token === "background" ? "Page surface" : `${token[0].toUpperCase()}${token.slice(1)} color`}</span></div></div>)}</div></section>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>Dark mode</h2><CodeBlock label="html" code={'<html class="dark">\n  <!-- application -->\n</html>'} /><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Toggle the document class and persist the preference in your app. The library provides the tokens; your app owns the preference.</p></section>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>Typography</h2><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">Fonts are loaded by each app. Set the following variables to use your chosen families. Without them, components use system fonts.</p><CodeBlock label="css" code={':root {\n  --elements-font-sans: "Space Grotesk", sans-serif;\n  --elements-font-mono: "JetBrains Mono", monospace;\n}'} /><div className="type-specimen flex gap-[30px] items-center py-6 px-0 [&_>_span]:text-[56px] [&_>_span]:leading-[1] [&_p]:text-[18px] [&_code]:text-muted-foreground"><span>Aa</span><div><p>Considered in every detail.</p><code>font-sans / font-mono</code></div></div></section>
    <section className="doc-section mt-10 [&_>_h2]:mb-4 max-[700px]:mt-8"><h2>Radius</h2><p className="body-copy text-muted-foreground text-[14px] leading-[1.8] mb-4">The base radius is 0.75rem. The theme derives the Tailwind radius scale from this value.</p><CodeBlock label="css" code={':root {\n  --radius: 0.75rem;\n}'} /></section>
  </article>;
}
